### ISSUE TITLE
Unlocked Balance + sweep_mined bug

### ISSUE THREAD

**Issue by BorisCryptoWave** [unprll-project/unprll#2]
After receiving a block, when i sweep_mined on my wallet it gives me Error: No unsweeped outputs found. Then some minutes later, when i refresh wallet, it shows this block found in unlocked balance. But minutes after this, I need to sweep_mined if I really want them in unlocked balance, if I don't, i'm not able to transfer them anywhere.

**Comment by christobias** [comment]
This isn't technically a bug because that is how the wallet was designed. I can either 1) Show the mined balance separate to your Mining Account balance, or 2) Notify you when there are pending unsweeped outputs.

However I think I should make it such that your outputs could be spent even with other outputs pending

**Comment by christobias** [comment]
I'll add code to notify the user in case any unsweeped outputs are remaining
